title: Jake Gearon's Research Home # your name (or website title) here
logo: "images/Profile.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Second-year Masters student at the University of Texas at Austin | Advised by Ron Steel & Cornel Olariu | Dynamic
  Stratigraphy Group <a href = "mailto: jake.gearon@gmail.com">jake.gearon@gmail.com</a>
  <br><br>
  A Sedimentologist focused on constraining morphology, sedimentary dynamics, depositional architectures, and
  sediment-water interfaces in the modern and ancient using remote sensing, data analytics, and old-fashioned field work
  <br><br>
  <a href="https://twitter.com/JakeGearon">My Twitter</a> <br><br>
  <a href="https://www.linkedin.com/in/jake-gearon-742767148/">My LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: UA-178433431-1 # your Google Analytics tracking ID here
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
