title: James (Jake) Gearon # your name (or website title) here
logo: "/images/UNADJUSTEDNONRAW_thumb_534.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A Sedimentologist with a focus on constraining morphology in the modern in ancient using remote sensing, data analytics, and old fashioned field work
  <br><br>
  First-year Masters student at the University of Texas at Austin | Advised by Ron Steel & Cornel Olariu | Dynamic Stratigraphy Group 
  <br><br>
  <a href="https://www.linkedin.com/in/james-gearon-742767148/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
