name: Sync Obsidian Notes

on:
  push:
    paths:
      - 'PublicNotes/**'
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  sync-notes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-frontmatter
    
    - name: Sync notes
      run: python scripts/sync_obsidian.py
      
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add _random-musings/
        git commit -m "Auto-sync Obsidian notes" || echo "No changes to commit"
        git push 